name: sample_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies
dependencies:
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.3.9
  extensions_kit: ^1.0.3
  flutter:
    sdk: flutter
  get: ^4.6.6
  the_validator: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf

    - family: medium
      fonts:
        - asset: assets/fonts/Urbanist-Medium.ttf

    - family: regular
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf

    - family: semiBold
      fonts:
        - asset: assets/fonts/Urbanist-SemiBold.ttf
